# /gate/source/addSource sourceA Extended
# # /gate/source/sourceA/gps/type Point
# /gate/source/sourceA/gps/pos/type Volume
# /gate/source/sourceA/gps/shape Sphere
# /gate/source/sourceA/gps/radius 0.625 cm
# /gate/source/sourceA/gps/pos/centre 0 0 0 cm
# /gate/source/sourceA/setActivity 0.25 MBq
# # Definie which positronium decay use in the simulation
# /gate/source/sourceA/setType pPs
# # Set enable emission of deexcitation gamma ( prompt gamma ) and its energy

# /gate/source/sourceA/setEnableDeexcitation true
# /gate/source/sourceA/setPromptGammaEnergy 1077 keV
# /gate/source/sourceA/setPostroniumLifetime pPs 0.22 ns
# # /gate/source/sourceA/setPostroniumLifetime oPs 1.9 ns
# # /gate/source/sourceA/setFixedEmissionDirection 1 0 0

# # /gate/source/sourceA/setEnableFixedEmissionDirection true

# /gate/source/addSource sourceC Extended
# # /gate/source/sourceA/gps/type Point
# /gate/source/sourceC/gps/pos/type Volume
# /gate/source/sourceC/gps/shape Sphere
# /gate/source/sourceC/gps/radius 0.625 cm
# /gate/source/sourceC/gps/pos/centre 0 0 0 cm
# /gate/source/sourceC/setActivity 0.25 MBq
# # Definie which positronium decay use in the simulation
# /gate/source/sourceC/setType pPs
# # Set enable emission of deexcitation gamma ( prompt gamma ) and its energy
# /gate/source/sourceC/setEnableDeexcitation true
# /gate/source/sourceC/setPromptGammaEnergy 1077 keV
# /gate/source/sourceC/setPostroniumLifetime pPs 2.2 ns

# /gate/source/addSource sourceD Extended
# # /gate/source/sourceA/gps/type Point
# /gate/source/sourceD/gps/pos/type Volume
# /gate/source/sourceD/gps/shape Sphere
# /gate/source/sourceD/gps/radius 0.625 cm
# /gate/source/sourceD/gps/pos/centre 0 0 0 cm
# /gate/source/sourceD/setActivity 0.5 MBq
# # Definie which positronium decay use in the simulation
# /gate/source/sourceD/setType pPs
# # Set enable emission of deexcitation gamma ( prompt gamma ) and its energy
# /gate/source/sourceD/setEnableDeexcitation true
# /gate/source/sourceD/setPromptGammaEnergy 1077 keV
# /gate/source/sourceD/setPostroniumLifetime pPs 0.44 ns


/gate/source/addSource sourceA Extended
# /gate/source/sourceA/gps/type Point
/gate/source/sourceA/gps/shape Cylinder
/gate/source/sourceA/gps/radius 0.625 cm
/gate/source/sourceA/gps/halfz 1. cm
/gate/source/sourceA/gps/pos/centre 0 0 0 cm
/gate/source/sourceA/setActivity 0.25 MBq
# Definie which positronium decay use in the simulation
/gate/source/sourceA/setType pPs
# Set enable emission of deexcitation gamma ( prompt gamma ) and its energy

/gate/source/sourceA/setEnableDeexcitation true
/gate/source/sourceA/setPromptGammaEnergy 1077 keV
/gate/source/sourceA/setPostroniumLifetime pPs 0.22 ns
# /gate/source/sourceA/setPostroniumLifetime oPs 1.9 ns
# /gate/source/sourceA/setFixedEmissionDirection 1 0 0

# /gate/source/sourceA/setEnableFixedEmissionDirection true

/gate/source/addSource sourceC Extended
# /gate/source/sourceA/gps/type Point
/gate/source/sourceC/gps/shape Cylinder
/gate/source/sourceC/gps/radius 0.625 cm
/gate/source/sourceC/gps/halfz 1. cm
/gate/source/sourceC/gps/pos/centre 0 0 0 cm
/gate/source/sourceC/setActivity 0.25 MBq
# Definie which positronium decay use in the simulation
/gate/source/sourceC/setType pPs
# Set enable emission of deexcitation gamma ( prompt gamma ) and its energy
/gate/source/sourceC/setEnableDeexcitation true
/gate/source/sourceC/setPromptGammaEnergy 1077 keV
/gate/source/sourceC/setPostroniumLifetime pPs 2.0 ns

/gate/source/addSource sourceD Extended
# /gate/source/sourceA/gps/type Point
/gate/source/sourceD/gps/shape Cylinder
/gate/source/sourceD/gps/radius 0.625 cm
/gate/source/sourceD/gps/halfz 1. cm

/gate/source/sourceD/gps/pos/centre 0 0 0 cm
/gate/source/sourceD/setActivity 0.5 MBq
# Definie which positronium decay use in the simulation
/gate/source/sourceD/setType pPs
# Set enable emission of deexcitation gamma ( prompt gamma ) and its energy
/gate/source/sourceD/setEnableDeexcitation true
/gate/source/sourceD/setPromptGammaEnergy 1077 keV
/gate/source/sourceD/setPostroniumLifetime pPs 0.44 ns