/gate/actor/addActor DoseActor                dose
/gate/actor/dose/attachTo                     D1
#/gate/actor/dose/stepHitType                  random
/gate/actor/dose/setDoseAlgorithm             VolumeWeighting
/gate/actor/dose/setResolution    10 10 10
/gate/actor/dose/enableEdep             true
/gate/actor/dose/enableDose             true
/gate/actor/dose/enableNumberOfHits     true
/gate/actor/dose/save                         {ACTOR_OUTPUT_PATH}/dose.root